import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Auth & Onboarding
      'onboarding_title_part1': 'Optimize Your',
      'onboarding_title_part2': 'West African Business',
      'onboarding_subtitle': 'Make smarter production, logistics, and budget decisions, even in challenging environments.',
      'niamey_hub_active': 'Niamey Hub Active',
      'live_logistics': 'LIVE LOGISTICS',
      'welcome_to_optiflow': 'Welcome to OptiFlow',
      'optimize_prod_log': 'Optimize production & logistics in West Africa',
      'phone_auth_title': 'Enter your phone\nnumber',
      'phone_auth_subtitle': 'We\'ll send a verification code to\nsecure your logistics account.',
      'send_code': 'Send verification code',
      'terms_privacy_prefix': 'By continuing, you agree to our ',
      'terms_of_service': 'Terms of Service',
      'and': ' and ',
      'privacy_policy': 'Privacy Policy.',
      'verify_number': 'Verify your number',
      'enter_otp_prefix': 'Enter the 6-digit code sent to ',
      'enter_otp_suffix': '. This helps us secure your logistics hub access.',
      'resend_available': 'Resend available in',
      'resend_code': 'RESEND CODE',
      'verify_continue': 'Verify and continue',
      'welcome': 'Welcome to OptiFlow!',
      'select_role': 'Select your role.',
      'continue': 'Continue',
      'business_setup': 'Set Up Your\nBusiness',
      'business_name': 'Business Name',
      'business_type': 'Business Type',
      'country_ops': 'Country of Operation',
      'currency': 'Currency',
      'primary_city': 'Primary City',
      'complete_setup': 'Complete Setup',
      'phone_error': 'Please enter a valid phone number',
      'otp_error': 'Please enter the complete 6-digit code',
      'secure_sync': 'SECURE SYNC',
      'instant_sms': 'INSTANT SMS',
      'step': 'Step',
      'business_setup_subtitle': 'Tell us about your business to get started.',
      'manufacturing': 'Manufacturing',
      'distribution': 'Distribution',
      'business_owner': 'Business Owner',
      'manager': 'Manager',
      'driver': 'Driver',
      'admin': 'Admin',
      'role_owner_desc': 'Manage assets and high-level strategy.',
      'role_manager_desc': 'Optimize production or logistics.',
      'role_driver_desc': 'Handle routes and deliveries.',
      'role_admin_desc': 'Platform-wide management and analytics.',
      'full_name': 'Full Name',
      'email_address': 'Email Address',
      'forgot_password': 'Forgot Password?',
      'forgot_password_title': 'Reset Password',
      'forgot_password_subtitle': 'Enter your email address and we\'ll send you a link to reset your password.',
      'send_reset_link': 'Send Reset Link',
      'reset_link_sent': 'Reset link sent! Check your email.',
      'email_not_found': 'No account found with this email.',
      'login_failed': 'Login failed',
      'wrong_password': 'Wrong password provided.',
      'invalid_email_address': 'Invalid email address',
      'password_min_length': 'Password must be at least 6 characters',
      'password_updated_successfully': 'Password updated successfully! Welcome to OptiFlow.',
      'failed_to_update_password': 'Failed to update password. Try logging in again.',
      'location_saved_successfully': 'Location saved successfully',
      'verification_id_missing': 'Verification ID is missing. Please request a new code.',
      'verification_failed': 'Verification failed. Please try again.',
      'unexpected_error': 'Unexpected error occurred. Please try again later.',
      'user_data_not_found': 'User data not found in registration records.',
      'error_prefix': 'Error',
      'payment_failed': 'Payment Failed',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'retype_password': 'Retype password',
      'passwords_do_not_match': 'Passwords do not match.',
      'location_name_hint': 'e.g., Central Warehouse, Shop A',
      'enter_name': 'Enter name',
      'address_hint': 'Street name, District, City',
      'enter_address': 'Enter address',

      // Home & Core
      'home_title': 'OptiFlow',
      'welcome_user_prefix': 'Hello',
      'dashboard_subtitle': 'Ready to optimize your Niamey hub\noperations?',
      'total_products': 'TOTAL\nPRODUCTS',
      'active_locations': 'ACTIVE\nLOCATIONS',
      'savings_mtd': 'SAVINGS\n(MTD)',
      'ops_optimization': 'Operations Optimization',
      'recent_results': 'Recent Results',
      'view_all': 'View All',
      'last_optimization': 'LAST OPTIMIZATION',
      'network_strength': 'LIVE NETWORK STRENGTH',
      'operational_resilience': 'Operational Resilience',
      'saved_results': 'Saved Results',
      'search_scenarios': 'Search saved scenarios...',
      'home_tab': 'Home',
      'all': 'All',
      'product_mix': 'Product Mix',
      'transport': 'Transport',
      'routes': 'Routes',
      'budget': 'Budget',
      'efficiency_gain': 'Efficiency Gain',
      'savings_identified': 'Savings Identified',
      'deep_dive': 'Deep Dive',
      'view': 'View',
      'profile': 'Profile',
      'activity_stats': 'Activity Stats',
      'optimizations': 'OPTIMIZATIONS',
      'fuel_saved': 'FUEL SAVED',
      'cost_saved': 'COST SAVED',
      'contact_info': 'Contact Information',
      'location': 'LOCATION',
      'business_details': 'Business Details',
      'business_id': 'BUSINESS ID',
      'role_label': 'ROLE',
      'joined_date': 'JOINED DATE',
      'status_label': 'STATUS',
      'active_status': 'ACTIVE',
      'account_settings': 'Account Settings',
      'edit_profile': 'Edit Profile',
      'security_password': 'Security & Password',
      'notification_prefs': 'Notification Preferences',
      'regional_prefs': 'Regional Preferences',
      'sign_out': 'Sign Out',

      // Product Mix Module
      'optimization': 'Optimization',
      'products': 'Products',
      'resources': 'Resources',
      'search_products': 'Search products...',
      'products_total': 'products total',
      'add_product': 'Add Product',
      'add_new_product': 'Add New Product',
      'product_params_desc': 'Define production parameters and optimize resource allocation for West African distribution hubs.',
      'upload_photo': 'Upload Product Photo',
      'high_quality_img': 'High-quality JPG or PNG',
      'unit_type': 'Unit Type',
      'currency_hub': 'Currency Hub',
      'unit_financials': 'Unit Financials',
      'selling_price': 'SELLING PRICE',
      'production_cost': 'PRODUCTION COST',
      'resource_requirements': 'Resource Requirements',
      'add_resource': 'Add Resource',
      'save_product': 'Save Product',
      'save_desc': 'Once saved, this product will be available for route planning and scenario modeling.',
      'resource_constraints': 'Resource Constraints',
      'resource_desc': 'Resources are the raw materials, labor, and machine time available for production. Enter your maximum available quantities.',
      'current_audit': 'CURRENT AUDIT',
      'resources_defined': 'resources\ndéfinies',
      'save_resources': 'Save Resources',
      'allocation': 'Allocation',
      'optimal_plan': 'Optimal Production\nPlan',
      'opt_completed': 'Optimization completed for Q3 Niamey Hub',
      'total_profit': 'TOTAL PROFIT',
      'units_to_produce': 'TOTAL UNITS TO PRODUCE',
      'resource_utilization': 'RESOURCE UTILIZATION',
      'production_breakdown': 'Production Breakdown',
      'breakdown_desc': 'Detailed allocation by product category',
      'compare_last_month': 'Compare to Last Month',
      'save_result': 'Save Result',
      'export_pdf': 'Export PDF',
      'share_whatsapp': 'Share via WhatsApp',

      // Transport Module
      'transport_cost_input': 'Transport Cost\nInput',
      'logistics_params_desc': 'Define regional logistics parameters for West African hubs.',
      'history': 'History',
      'border_crossing': 'BORDER CROSSING',
      'supply_points': 'Supply Points',
      'factories': 'FACTORIES',
      'available_supply': 'AVAILABLE SUPPLY',
      'storage_cost': 'STORAGE COST',
      'add_supply_point': 'Add Supply Point',
      'demand_points': 'Demand Points',
      'retailers': 'RETAILERS',
      'target_demand': 'TARGET DEMAND',
      'lead_time_max': 'LEAD TIME MAX',
      'add_demand_point': 'Add Demand Point',
      'cross_border_active': 'CROSS-BORDER CORRIDOR ACTIVE',
      'route_mode': 'Route Mode',
      'opt_algo_desc': 'Optimization algorithm prioritizes paved roads and arterial expressways through Zinder and Katsina.',
      'vehicle_profile': 'Vehicle Profile',
      'run_transport_opt': 'Run Transport Optimization',
      'add_location': 'Add Location',
      'location_name': 'Location Name',
      'location_type': 'Location Type',
      'full_address': 'Full Address',
      'map_location': 'Map Location',
      'tap_drop_pin': 'Tap to drop pin',
      'gps_coordinates': 'GPS COORDINATES',
      'latitude_label': 'LATITUDE',
      'longitude_label': 'LONGITUDE',
      'get_current_location': 'Get Current Location',
      'available_supply_qty': 'Available Supply Quantity',
      'additional_notes': 'Additional Notes',
      'location_data_tip': 'Accurate location data improves logistics route optimization by up to 22% in West African urban corridors.',
      'save_location': 'Save Location',
      'delete_location': 'Delete Location',
      'opt_transport_plan': 'Optimal Transport\nPlan',
      'opt_complete': 'OPTIMIZATION COMPLETE',
      'total_transport_cost': 'TOTAL TRANSPORT COST',
      'total_distance': 'TOTAL DISTANCE',
      'fuel_required': 'FUEL REQUIRED',
      'estimated_consumption': 'Estimated consumption:',
      'route_allocation': 'Route\nAllocation',
      'origin': 'ORIGIN',
      'destination': 'DESTINATION',
      'vehicle_type': 'VEHICLE\nTYPE',
      'route_viz': 'Route Network\nVisualization',
      'viz_desc': 'Visualizing 1,200km across 3\nprimary hubs',
      'plan_routes': 'Plan Routes',

      // Route Module
      'search_rural': 'Search rural villages or hubs...',
      'offline_maps_active': 'Offline Maps Active: Niamey-Tillabéri Region',
      'route_planner': 'Route Planner',
      'dest_selected': 'destinations selected',
      'est_time': 'EST. TIME',
      'optimize_route': 'Optimize Route',
      'opt_delivery_route': 'Optimized Delivery\nRoute',
      'route_calculated': 'Route calculated for Niamey Hub\nOperations • Today, 08:45 AM',
      'live_preview': 'LIVE PREVIEW',
      'route_summary': 'ROUTE SUMMARY',
      'num_stops': 'Number of Stops',
      'opt_sequence': 'Optimized\nSequence',
      'start_navigation': 'Start Navigation',
      'save_route': 'Save Route',
      'share_sms': 'Share via\nSMS',
      'confirm_delivery': 'Confirm Delivery',
      'active_route': 'ACTIVE ROUTE',
      'safe_work': 'SAFE WORK',
      'live_feed': 'LIVE FEED',
      'goods_verification': 'Goods Verification',
      'goods_ver_desc': 'Ensure all security seals are visible and the package is placed in the designated safe zone.',
      'ver_stamp': 'VERIFICATION STAMP',
      'timestamp': 'TIMESTAMP',
      'recipient_address': 'Recipient Address',
      'customer_name': 'CUSTOMER NAME',
      'delivery_point': 'DELIVERY POINT',
      'regional_ops': 'Regional Operations:',
      'digital_signature': 'Digital Signature',
      'clear_canvas': 'CLEAR CANVAS',
      'sign_here': 'Sign here...',
      'signing_confirm': 'By signing, you confirm that the goods were received in perfect condition.',
      'submit_proof': 'Submit Proof',
      'arrived_status': 'Arrived',
      'current_stop': 'CURRENT STOP',
      'next_stop': 'NEXT STOP',

      // Budget Module
      'budget_constraints_title': 'Set Your\nBudget\nConstraints',
      'budget_constraints_desc': 'Optimize resource allocation across West African hubs to maximize throughput while minimizing operational overhead.',
      'total_budget_amount': 'TOTAL BUDGET AMOUNT',
      'budget_rec_desc': 'Recommended based on Q3 Niamey Hub throughput.',
      'dept_allocation': 'Departmental\nAllocation',
      'regional_allocation_budget': 'Regional\nAllocation',
      'vendor_split': 'Vendor\nSplit',
      'seasonal_adjust': 'Seasonal\nAdjust',
      'constraints_label': 'Constraints',
      'min_profit_target': 'Min Profit Target',
      'max_labor_cost': 'Max Labor Cost',
      'strict_compliance': 'STRICT COMPLIANCE',
      'compliance_desc': 'Ensure all allocations strictly adhere to regional tax regulations and labor laws.',
      'run_budget_opt': 'Run Budget Optimization',
      'est_compute_time': 'Estimated compute time:',
      'opt_budget_allocation': 'Optimal Budget\nAllocation',
      'budget_result_desc': 'Strategic distribution calculated based on Q3 logistics demand and current fuel volatility in West African corridors.',
      'apply_budget': 'Apply\nBudget',
      'total_budget': 'TOTAL BUDGET',
      'expected_roi': 'EXPECTED ROI',
      'remaining_buffer': 'REMAINING BUFFER',
      'risk_mitigation': 'Risk mitigation',
      'allocation_dept': 'Allocation by\nDepartment',
      'current_rec': 'CURRENT\nRECOMMENDATION',
      'regional_breakdown': 'Regional Breakdown',
      'opt_insight': 'Optimization Insight',

      // Driver Module
      'good_morning': 'Good morning,',
      'ready_today_routes': 'Ready for today\'s routes?',
      'syncing_offline': 'Syncing Offline Data...',
      'today_summary': 'Today\'s Summary',
      'deliveries': 'Deliveries',
      'drive_time': 'Drive Time',
      'distance_label': 'Distance',
      'stops_left': 'STOPS LEFT',
      'pending_routes': 'Pending Routes',
      'completed_status': 'Completed',
      'start_delivery': 'Start Delivery',
      'today_routes': 'Today\'s Routes',
      'assigned_logistics': 'Assigned logistics for',
      'priority_route': 'PRIORITY ROUTE',
      'rural_route': 'RURAL ROUTE',
      'offline_maps_avail': 'OFFLINE MAPS AVAILABLE',
      'view_details': 'View Details',
      'refresh_routes': 'Refresh Routes',
      'join_fleet': 'Join a Fleet',
      'enter_code': 'Enter Company Code',
      'fleet_id_hint': 'e.g., OPT-ABC-123',
      'join_label': 'Join',
      'invalid_code': 'Invalid Code',

      // Settings & Support
      'settings_title': 'Settings',
      'settings_desc': 'Tailor your operational environment for peak efficiency across West African corridors.',
      'language_label': 'Language',
      'notifications_label': 'Notifications',
      'push_notifications': 'Push Notifications',
      'opt_alerts': 'Optimization Alerts',
      'budget_watch': 'Budget Watch',
      'route_changes': 'Route Changes',
      'sms_fallback': 'SMS Fallback',
      'sms_fallback_desc': 'Vital alerts when data connection is low',
      'map_settings': 'Map Settings',
      'offline_maps_label': 'Offline Maps',
      'download_corridor': 'Download Corridor',
      'offline_storage': 'Offline Storage',
      'storage_health': 'Storage Health',
      'cache_usage': 'Cache Usage',
      'clear_cache': 'CLEAR CACHE',
      'save_changes': 'Save Changes',
      'notification_title': 'Notifications',
      'notification_desc': 'Stay updated on your fleet and routes.',
      'today_label': 'TODAY',
      'yesterday_label': 'YESTERDAY',
      'earlier_label': 'EARLIER',
      'help_title': 'How can we help?',
      'help_desc': 'Search for guides or browse categories below.',
      'search_help': 'Search for route optimization...',
      'getting_started': 'Getting Started',
      'driver_guide': 'Driver Guide',
      'video_tutorials': 'Video Tutorials',
      'quick_start_guides': 'Quick Start Guides',
      'faq_label': 'Frequently Asked Questions',
      'still_need_help': 'Still need help?',
      'support_team_avail': 'Our support team is available 24/7 to assist with your logistics needs.',
      'contact_support': 'Contact Support',
      'support_center': 'Support Center',
      'support_desc': 'How can we help you streamline your\nroute today?',
      'report_issue': 'Report Issue',
      'rate_app': 'Rate App',
      'direct_contact': 'Direct Contact',
      'whatsapp_support': 'WhatsApp Support',
      'chat_whatsapp': 'Chat on WhatsApp',
      'service_hours': 'Service Hours',
      'service_hours_desc': 'Our team is available across West Africa standard times.',
      'quick_faq': 'Quick FAQ',

      // Export
      'export_result': 'Export Optimization Result',
      'select_method': 'Select your preferred delivery method',
      'whatsapp_label': 'WhatsApp',
      'instant_share_manager': 'Instant share to fleet manager',
      'email_label': 'Email',
      'full_csv': 'Full breakdown CSV',
      'download_pdf_official': 'Download PDF',
      'official_report': 'Official report',
      'sms_label': 'SMS',
      'sms_short_link': 'Send as short link to driver',
      'recommended_label': 'RECOMMENDED',
      'done_label': 'Done',

      // Admin
      'admin_dashboard_title': 'Platform Overview',
      'add_admin': 'Add Admin',
      'review_reports': 'Review Reports',
      'send_broadcast': 'Send Broadcast',
      'total_users': 'Total Users',
      'active_businesses': 'Active Businesses',
      'opts_run': 'Optimizations Run',
      'monthly_revenue': 'Monthly Revenue',
      'user_growth': 'User Growth Analysis',
      'recent_activity': 'Recent Activity',
      'country_perf': 'Country Performance Hub',
      'user_mgmt_title': 'User Management',
      'user_mgmt_desc': 'Manage platform access, roles, and business associations.',
      'export_users': 'Export Users',
      'roles_filter': 'Roles:',
      'user_id_label_admin': 'USER ID',
      'phone_label_admin': 'PHONE',
      'business_label': 'BUSINESS',
      'actions_label': 'ACTIONS',
      'total_active_label': 'TOTAL ACTIVE',
      'pending_ver_label': 'PENDING VERIFICATION',
      'total_bus_label': 'TOTAL BUSINESSES',
      'blocked_users_label': 'BLOCKED USERS',
      'sys_settings_title': 'System Settings',
      'sys_settings_desc': 'Configure global parameters and platform defaults for OptiFlow\'s West African logistics network.',
      'currency_settings_title': 'Currency Settings',
      'base_currency_label': 'BASE CURRENCY',
      'active_exch_rates': 'ACTIVE EXCHANGE RATES',
      'regional_content_title': 'Regional Content',
      'supported_langs': 'SUPPORTED LANGUAGES',
      'optimization_settings_title': 'Optimization',
      'route_timeout_label': 'ROUTE TIMEOUT',
      'max_fleet_density_label': 'DENSITÉ FLOTTE MAX',
      'notification_api_title': 'Notification & API',
      'sms_gateway_label': 'SMS Gateway',
      'email_int_label': 'Email Integration',
      'discard_changes_label': 'Discard Changes',
      'broadcast_title': 'Send Broadcast',
      'broadcast_desc': 'Reach your logistics partners and users instantly with regional or global announcements.',
      'target_audience_label': 'Target Audience',
      'notif_content_label': 'Notification Content',
      'notif_title_label': 'Notification Title',
      'msg_body_label': 'Message Body',
      'attach_img_label': 'Attach Image',
      'add_deep_link_label': 'Add Deep Link',
      'delivery_schedule_label': 'Delivery Schedule',
      'send_now_label': 'Send Now',
      'schedule_later_label': 'Schedule for later',
      'audience_reach_label': 'Audience Reach Estimate',
      'broadcast_estimate_prefix': 'Your message will be broadcasted to approximately',
      'users_across_wa': 'users across West Africa.',
    },
    'fr': {
      // Auth & Onboarding
      'onboarding_title_part1': 'Optimisez votre',
      'onboarding_title_part2': 'Entreprise Ouest-Africaine',
      'onboarding_subtitle': 'Prenez des décisions plus intelligentes en matière de production, de logistique et de budget, même dans des environnements difficiles.',
      'niamey_hub_active': 'Hub de Niamey Actif',
      'live_logistics': 'LOGISTIQUE EN DIRECT',
      'welcome_to_optiflow': 'Bienvenue sur OptiFlow',
      'optimize_prod_log': 'Optimisez la production et la logistique en Afrique de l\'Ouest',
      'phone_auth_title': 'Entrez votre numéro\nde téléphone',
      'phone_auth_subtitle': 'Nous vous enverrons un code de vérification pour sécuriser votre compte logistique.',
      'send_code': 'Envoyer le code de vérification',
      'terms_privacy_prefix': 'En continuant, vous acceptez nos ',
      'terms_of_service': 'Conditions d\'Utilisation',
      'and': ' et notre ',
      'privacy_policy': 'Politique de Confidentialité.',
      'verify_number': 'Vérifiez votre numéro',
      'enter_otp_prefix': 'Entrez le code à 6 chiffres envoyé au ',
      'enter_otp_suffix': '. Cela nous aide à sécuriser votre accès au hub logistique.',
      'resend_available': 'Renvoyer disponible dans',
      'resend_code': 'RENVOYER LE CODE',
      'verify_continue': 'Vérifier et continuer',
      'welcome': 'Bienvenue sur OptiFlow !',
      'select_role': 'Sélectionnez votre rôle.',
      'continue': 'Continuer',
      'business_setup': 'Configurez Votre\nEntreprise',
      'business_name': 'Nom de l\'entreprise',
      'business_type': 'Type d\'entreprise',
      'country_ops': 'Pays d\'opération',
      'currency': 'Devise',
      'primary_city': 'Ville principale',
      'complete_setup': 'Terminer la configuration',
      'phone_error': 'Veuillez entrer un numéro de téléphone valide',
      'otp_error': 'Veuillez entrer le code complet à 6 chiffres',
      'secure_sync': 'SYNCHRO SÉCURISÉE',
      'instant_sms': 'SMS INSTANTANÉ',
      'step': 'Étape',
      'business_setup_subtitle': 'Parlez-nous de votre entreprise pour commencer.',
      'manufacturing': 'Fabrication',
      'distribution': 'Distribution',
      'business_owner': 'Propriétaire d\'Entreprise',
      'manager': 'Gestionnaire',
      'driver': 'Chauffeur',
      'admin': 'Admin',
      'role_owner_desc': 'Gérez les actifs et la stratégie de haut niveau.',
      'role_manager_desc': 'Optimisez la production ou la logistique.',
      'role_driver_desc': 'Gérez les itinéraires et les livraisons.',
      'role_admin_desc': 'Gestion et analyse de la plateforme.',
      'full_name': 'Nom complet',
      'email_address': 'Adresse e-mail',
      'forgot_password': 'Mot de passe oublié ?',
      'forgot_password_title': 'Réinitialiser le mot de passe',
      'forgot_password_subtitle': 'Entrez votre adresse e-mail et nous vous enverrons un lien pour réinitialiser votre mot de passe.',
      'send_reset_link': 'Envoyer le lien',
      'reset_link_sent': 'Lien envoyé ! Consultez vos e-mails.',
      'email_not_found': 'Aucun compte trouvé avec cet e-mail.',
      'login_failed': 'Échec de la connexion',
      'wrong_password': 'Mot de passe incorrect.',
      'invalid_email_address': 'Adresse e-mail invalide',
      'password_min_length': 'Le mot de passe doit contenir au moins 6 caractères',
      'password_updated_successfully': 'Mot de passe mis à jour avec succès ! Bienvenue sur OptiFlow.',
      'failed_to_update_password': 'Impossible de mettre à jour le mot de passe. Réessayez en vous reconnectant.',
      'location_saved_successfully': 'Emplacement enregistré avec succès',
      'verification_id_missing': 'L’ID de vérification est manquant. Veuillez demander un nouveau code.',
      'verification_failed': 'Échec de la vérification. Veuillez réessayer.',
      'unexpected_error': 'Une erreur inattendue est survenue. Veuillez réessayer plus tard.',
      'user_data_not_found': 'Données utilisateur introuvables dans les enregistrements.',
      'error_prefix': 'Erreur',
      'payment_failed': 'Échec du paiement',

      // Home & Core
      'home_title': 'OptiFlow',
      'welcome_user_prefix': 'Bonjour',
      'dashboard_subtitle': 'Prêt à optimiser les opérations de votre hub de Niamey ?',
      'total_products': 'TOTAL\nPRODUITS',
      'active_locations': 'SITES\nACTIFS',
      'savings_mtd': 'ÉCONOMIES\n(MTD)',
      'ops_optimization': 'Optimisation des Opérations',
      'recent_results': 'Résultats Récents',
      'home_tab': 'Accueil',
      'view_all': 'Tout Voir',
      'last_optimization': 'DERNIÈRE OPTIMISATION',
      'network_strength': 'FORCE DU RÉSEAU EN DIRECT',
      'operational_resilience': 'Résilience Opérationnelle',
      'saved_results': 'Résultats Enregistrés',
      'search_scenarios': 'Rechercher des scénarios...',
      'all': 'Tout',
      'product_mix': 'Mix Produit',
      'transport': 'Transport',
      'routes': 'Itinéraires',
      'budget': 'Budget',
      'efficiency_gain': 'Gain d\'Efficacité',
      'savings_identified': 'Économies Identifiées',
      'deep_dive': 'Analyse Approfondie',
      'view': 'Voir',
      'profile': 'Profil',
      'activity_stats': 'Stats d\'Activité',
      'optimizations': 'OPTIMISATIONS',
      'fuel_saved': 'CARBURANT ÉCONOMISÉ',
      'cost_saved': 'COÛT ÉCONOMISÉ',
      'contact_info': 'Coordonnées',
      'location': 'EMPLACEMENT',
      'business_details': 'Détails de l\'Entreprise',
      'business_id': 'ID ENTREPRISE',
      'role_label': 'RÔLE',
      'joined_date': 'DATE D\'INSCRIPTION',
      'status_label': 'STATUT',
      'active_status': 'ACTIF',
      'account_settings': 'Paramètres du Compte',
      'edit_profile': 'Modifier le Profil',
      'security_password': 'Sécurité et Mot de Passe',
      'notification_prefs': 'Préférences de Notification',
      'regional_prefs': 'Préférences Régionales',
      'sign_out': 'Déconnexion',

      // Product Mix
      'optimization': 'Optimisation',
      'products': 'Produits',
      'resources': 'Ressources',
      'search_products': 'Rechercher des produits...',
      'products_total': 'produits au total',
      'add_product': 'Ajouter un Produit',
      'add_new_product': 'Nouveau Produit',
      'product_params_desc': 'Définissez les paramètres de production et optimisez l\'allocation des ressources.',
      'upload_photo': 'Télécharger une photo',
      'high_quality_img': 'JPG ou PNG de haute qualité',
      'unit_type': 'Type d\'unité',
      'currency_hub': 'Hub de Devise',
      'unit_financials': 'Finances de l\'Unité',
      'selling_price': 'PRIX DE VENTE',
      'production_cost': 'COÛT DE PRODUCTION',
      'resource_requirements': 'Besoins en Ressources',
      'add_resource': 'Ajouter Ressource',
      'save_product': 'Enregistrer le Produit',
      'save_desc': 'Une fois enregistré, ce produit sera disponible pour la planification.',
      'resource_constraints': 'Contraintes de Ressources',
      'resource_desc': 'Les ressources sont les matières premières, la main-d\'œuvre et le temps machine.',
      'current_audit': 'AUDIT ACTUEL',
      'resources_defined': 'ressources\ndéfinies',
      'save_resources': 'Enregistrer Ressources',
      'allocation': 'Allocation',
      'optimal_plan': 'Plan de Production\nOptimal',
      'opt_completed': 'Optimisation terminée pour le Hub de Niamey',
      'total_profit': 'PROFIT TOTAL',
      'units_to_produce': 'UNITÉS À PRODUIRE',
      'resource_utilization': 'UTILISATION RESSOURCES',
      'production_breakdown': 'Répartition de Production',
      'breakdown_desc': 'Allocation détaillée par catégorie',
      'compare_last_month': 'Comparer au mois dernier',
      'save_result': 'Enregistrer Résultat',
      'export_pdf': 'Exporter PDF',
      'share_whatsapp': 'Partager via WhatsApp',

      // Transport
      'transport_cost_input': 'Coût du Transport\nEntrée',
      'logistics_params_desc': 'Définir les paramètres logistiques régionaux.',
      'history': 'Historique',
      'border_crossing': 'PASSAGE FRONTIÈRE',
      'supply_points': 'Points d\'Approvisionnement',
      'factories': 'USINES',
      'available_supply': 'STOCK DISPONIBLE',
      'storage_cost': 'COÛT DE STOCKAGE',
      'add_supply_point': 'Ajouter Point d\'Appro',
      'demand_points': 'Points de Demande',
      'retailers': 'DÉTAILLANTS',
      'target_demand': 'DEMANDE CIBLE',
      'lead_time_max': 'DÉLAI MAX',
      'add_demand_point': 'Ajouter Point de Demande',
      'cross_border_active': 'CORRIDOR TRANSFRONTALIER ACTIF',
      'route_mode': 'Mode d\'Itinéraire',
      'opt_algo_desc': 'L\'algorithme privilégie les routes goudronnées et express.',
      'vehicle_profile': 'Profil du Véhicule',
      'run_transport_opt': 'Lancer l\'Optimisation',
      'add_location': 'Ajouter un Lieu',
      'location_name': 'Nom du Lieu',
      'location_type': 'Type de Lieu',
      'full_address': 'Adresse Complète',
      'map_location': 'Lieu sur la Carte',
      'tap_drop_pin': 'Appuyer pour épingler',
      'gps_coordinates': 'COORDONNÉES GPS',
      'latitude_label': 'LATITUDE',
      'longitude_label': 'LONGITUDE',
      'get_current_location': 'Ma Position Actuelle',
      'available_supply_qty': 'Quantité disponible',
      'additional_notes': 'Notes Additionnelles',
      'location_data_tip': 'Les données précises améliorent l\'optimisation de 22%.',
      'save_location': 'Enregistrer Lieu',
      'delete_location': 'Supprimer Lieu',
      'opt_transport_plan': 'Plan de Transport\nOptimal',
      'opt_complete': 'OPTIMISATION TERMINÉE',
      'total_transport_cost': 'COÛT TOTAL TRANSPORT',
      'total_distance': 'DISTANCE TOTALE',
      'fuel_required': 'CARBURANT REQUIS',
      'estimated_consumption': 'Consommation estimée :',
      'route_allocation': 'Allocation\nItinéraires',
      'origin': 'ORIGINE',
      'destination': 'DESTINATION',
      'vehicle_type': 'TYPE DE\nVÉHICULE',
      'route_viz': 'Visualisation du Réseau',
      'viz_desc': 'Visualisation sur 1 200 km',
      'plan_routes': 'Planifier les Routes',

      // Route
      'search_rural': 'Chercher villages ou hubs...',
      'offline_maps_active': 'Cartes Hors Ligne Actives : Région Niamey',
      'route_planner': 'Planificateur',
      'dest_selected': 'destinations choisies',
      'est_time': 'TEMPS EST.',
      'optimize_route': 'Optimiser l\'Itinéraire',
      'opt_delivery_route': 'Itinéraire de Livraison\nOptimisé',
      'route_calculated': 'Calculé pour le Hub de Niamey',
      'live_preview': 'APERÇU EN DIRECT',
      'route_summary': 'RÉSUMÉ DE L\'ITINÉRAIRE',
      'num_stops': 'Nombre d\'arrêts',
      'opt_sequence': 'Séquence\nOptimisée',
      'start_navigation': 'Démarrer Navigation',
      'save_route': 'Enregistrer Route',
      'share_sms': 'Partager par SMS',
      'confirm_delivery': 'Confirmer Livraison',
      'active_route': 'ROUTE ACTIVE',
      'safe_work': 'TRAVAIL SÛR',
      'live_feed': 'DIRECT',
      'goods_verification': 'Vérification Marchandises',
      'goods_ver_desc': 'Vérifiez les scellés et placez le colis en zone sûre.',
      'ver_stamp': 'TAMPON VÉRIF.',
      'timestamp': 'HORODATAGE',
      'recipient_address': 'Adresse Destinataire',
      'customer_name': 'NOM DU CLIENT',
      'delivery_point': 'POINT DE LIVRAISON',
      'regional_ops': 'Ops Régionales :',
      'digital_signature': 'Signature Digitale',
      'clear_canvas': 'EFFACER',
      'sign_here': 'Signez ici...',
      'signing_confirm': 'En signant, vous confirmez la bonne réception.',
      'submit_proof': 'Soumettre Preuve',
      'arrived_status': 'Arrivé',
      'current_stop': 'ARRÊT ACTUEL',
      'next_stop': 'ARRÊT SUIVANT',

      // Budget
      'budget_constraints_title': 'Contraintes de\nBudget',
      'budget_constraints_desc': 'Optimisez l\'allocation pour maximiser le débit.',
      'total_budget_amount': 'MONTANT TOTAL BUDGET',
      'budget_rec_desc': 'Basé sur le débit du Hub de Niamey.',
      'dept_allocation': 'Allocation par\nDépartement',
      'regional_allocation_budget': 'Répartition\nRégionale',
      'vendor_split': 'Répartition\nFournisseurs',
      'seasonal_adjust': 'Ajustement\nSaisonnier',
      'constraints_label': 'Contraintes',
      'min_profit_target': 'Objectif Profit Min',
      'max_labor_cost': 'Coût Main-d\'œuvre Max',
      'strict_compliance': 'CONFORMITÉ STRICTE',
      'compliance_desc': 'Respectez les lois fiscales et du travail.',
      'run_budget_opt': 'Lancer Optimisation',
      'est_compute_time': 'Temps de calcul estimé :',
      'opt_budget_allocation': 'Allocation Budget\nOptimale',
      'budget_result_desc': 'Répartition stratégique calculée selon la demande.',
      'apply_budget': 'Appliquer\nBudget',
      'total_budget': 'BUDGET TOTAL',
      'expected_roi': 'ROI ATTENDU',
      'remaining_buffer': 'RÉSERVE RESTANTE',
      'risk_mitigation': 'Atténuation risques',
      'allocation_dept': 'Allocation par\nDépartement',
      'current_rec': 'RECOMMANDATION\nACTUELLE',
      'regional_breakdown': 'Répartition Régionale',
      'opt_insight': 'Aperçu Optimisation',

      // Driver
      'good_morning': 'Bonjour,',
      'ready_today_routes': 'Prêt pour les routes du jour ?',
      'syncing_offline': 'Sync. données hors ligne...',
      'today_summary': 'Résumé du jour',
      'deliveries': 'Livraisons',
      'drive_time': 'Temps conduite',
      'distance_label': 'Distance',
      'stops_left': 'RESTANTS',
      'pending_routes': 'Routes en attente',
      'completed_status': 'Terminé',
      'start_delivery': 'Commencer Livraison',
      'today_routes': 'Routes d\'Aujourd\'hui',
      'assigned_logistics': 'Logistique assignée pour',
      'priority_route': 'ROUTE PRIORITAIRE',
      'rural_route': 'ROUTE RURALE',
      'offline_maps_avail': 'CARTES DISPONIBLES HORS LIGNE',
      'view_details': 'Voir Détails',
      'refresh_routes': 'Actualiser',
      'join_fleet': 'Rejoindre une flotte',
      'enter_code': 'Entrez le code entreprise',
      'fleet_id_hint': 'ex: OPT-ABC-123',
      'join_label': 'Rejoindre',
      'invalid_code': 'Code Invalide',

      // Settings
      'settings_title': 'Paramètres',
      'settings_desc': 'Adaptez votre environnement pour plus d\'efficacité.',
      'language_label': 'Langue',
      'notifications_label': 'Notifications',
      'push_notifications': 'Push',
      'opt_alerts': 'Alertes Optimisation',
      'budget_watch': 'Surveillance Budget',
      'route_changes': 'Changements Route',
      'sms_fallback': 'SMS de Secours',
      'sms_fallback_desc': 'Alertes vitales sans données',
      'map_settings': 'Paramètres Carte',
      'offline_maps_label': 'Paramètres Carte',
      'download_corridor': 'Télécharger Corridor',
      'offline_storage': 'Stockage Hors Ligne',
      'storage_health': 'Santé Stockage',
      'cache_usage': 'Usage Cache',
      'clear_cache': 'EFFACER CACHE',
      'save_changes': 'Enregistrer',
      'notification_title': 'Notifications',
      'notification_desc': 'Infos sur votre flotte.',
      'today_label': 'AUJOURD\'HUI',
      'yesterday_label': 'HIER',
      'earlier_label': 'PLUS TÔT',
      'help_title': 'Aide',
      'help_desc': 'Cherchez des guides.',
      'search_help': 'Chercher...',
      'getting_started': 'Démarrage',
      'driver_guide': 'Guide Chauffeur',
      'video_tutorials': 'Tutoriels Vidéo',
      'quick_start_guides': 'Guides Rapides',
      'faq_label': 'Questions Fréquentes',
      'still_need_help': 'Besoin d\'aide ?',
      'support_team_avail': 'Support dispo 24/7.',
      'contact_support': 'Contacter Support',
      'support_center': 'Centre de Support',
      'report_issue': 'Signaler Problème',
      'rate_app': 'Noter l\'App',
      'direct_contact': 'Contact Direct',
      'whatsapp_support': 'Support WhatsApp',
      'chat_whatsapp': 'Discuter sur WhatsApp',
      'service_hours': 'Heures de Service',
      'quick_faq': 'FAQ Rapide',

      // Export
      'export_result': 'Exporter Résultat',
      'select_method': 'Mode d\'envoi',
      'whatsapp_label': 'WhatsApp',
      'instant_share_manager': 'Partage rapide',
      'email_label': 'E-mail',
      'full_csv': 'CSV détaillé',
      'download_pdf_official': 'PDF',
      'official_report': 'Rapport officiel',
      'sms_label': 'SMS',
      'sms_short_link': 'Lien court pour chauffeur',
      'recommended_label': 'RECOMMANDÉ',
      'done_label': 'Terminé',

      // Admin
      'admin_dashboard_title': 'Aperçu Plateforme',
      'add_admin': 'Ajouter Admin',
      'review_reports': 'Rapports',
      'send_broadcast': 'Diffuser',
      'total_users': 'Utilisateurs Totaux',
      'active_businesses': 'Entreprises Actives',
      'opts_run': 'Optimisations',
      'monthly_revenue': 'Revenu Mensuel',
      'user_growth': 'Croissance',
      'recent_activity': 'Activité Récente',
      'country_perf': 'Performance par Pays',
      'user_mgmt_title': 'User Management',
      'user_mgmt_desc': 'Gestion des accès et des rôles.',
      'export_users': 'Exporter',
      'roles_filter': 'Rôles:',
      'user_id_label_admin': 'ID',
      'phone_label_admin': 'PHONE',
      'business_label': 'BUSINESS',
      'actions_label': 'ACTIONS',
      'total_active_label': 'TOTAL ACTIVE',
      'pending_ver_label': 'PENDING VERIFICATION',
      'total_bus_label': 'TOTAL BUSINESSES',
      'blocked_users_label': 'BLOCKED USERS',
      'sys_settings_title': 'System Settings',
      'sys_settings_desc': 'Configurez les paramètres globaux.',
      'currency_settings_title': 'Paramètres Devise',
      'base_currency_label': 'DEVISE DE BASE',
      'active_exch_rates': 'TAUX DE CHANGE',
      'regional_content_title': 'Contenu Régional',
      'supported_langs': 'LANGUES',
      'optimization_settings_title': 'Optimisation',
      'route_timeout_label': 'DÉLAI ROUTE',
      'max_fleet_density_label': 'DENSITÉ FLOTTE MAX',
      'notification_api_title': 'Notif & API',
      'sms_gateway_label': 'Passerelle SMS',
      'email_int_label': 'Intégration E-mail',
      'discard_changes_label': 'Annuler',
      'broadcast_title': 'Diffusion',
      'broadcast_desc': 'Envoyez des annonces.',
      'target_audience_label': 'Audience Cible',
      'notif_content_label': 'Contenu Notif',
      'notif_title_label': 'Titre Notif',
      'msg_body_label': 'Message',
      'attach_img_label': 'Joindre Image',
      'add_deep_link_label': 'Lien Profond',
      'delivery_schedule_label': 'Planning',
      'send_now_label': 'Envoyer',
      'schedule_later_label': 'Plus tard',
      'audience_reach_label': 'Portée Estimée',
      'broadcast_estimate_prefix': 'Votre message sera diffusé à environ',
      'users_across_wa': 'utilisateurs en Afrique de l\'Ouest.',
    },
    'ha': {
      // Auth & Onboarding
      'onboarding_title_part1': 'Inganta',
      'onboarding_title_part2': 'Kasuwancin ku na Yammacin Afirka',
      'onboarding_subtitle': 'Yanke shawara mafi kyau game da samarwa, kayan aiki, da kasafin kuɗi, koda a cikin yanayi mai wahala.',
      'niamey_hub_active': 'Niamey Hub yana Aiki',
      'live_logistics': 'LOGISTICS NA TAKE',
      'welcome_to_optiflow': 'Barka da zuwa OptiFlow!',
      'optimize_prod_log': 'Inganta samarwa da rarraba kaya a Yammacin Afirka',
      'phone_auth_title': 'Shigar da lambar\nwayar ku',
      'phone_auth_subtitle': 'Za mu aika lambar tabbatarwa don kiyaye asusun ku.',
      'send_code': 'Aika lambar tabbatarwa',
      'terms_privacy_prefix': 'Ta ci gaba, kun yarda da ',
      'terms_of_service': 'Sharuɗɗan Sabis',
      'and': ' da ',
      'privacy_policy': 'Manufar Sirri.',
      'verify_number': 'Tabbatar da lambar ku',
      'forgot_password': 'Kun manta kalmar sirri?',
      'forgot_password_title': 'Sake saita Kalmar Sirri',
      'forgot_password_subtitle': 'Shigar da adireshin imel ɗin ku kuma za mu aika muku da hanyar haɗi don sake saita kalmar sirrin ku.',
      'send_reset_link': 'Aika Hanyar Haɗin Sake Saita',
      'reset_link_sent': 'An aika hanyar haɗi! Duba imel ɗin ku.',
      'email_not_found': 'Ba a sami asusu da wannan imel ba.',
      'login_failed': 'Binciken shiga ya gaza',
      'wrong_password': 'Kalmar sirri ba daidai ba ce.',
      'invalid_email_address': 'Adireshin imel ba daidai ba ne',
      'password_min_length': 'Kalmar sirri dole ne ta kasance aƙalla haruffa 6',
      'password_updated_successfully': 'An sabunta kalmar sirri cikin nasara! Barka da zuwa OptiFlow.',
      'failed_to_update_password': 'An kasa sabunta kalmar sirri. Gwada sake shiga.',
      'location_saved_successfully': 'An adana wurin cikin nasara',
      'verification_id_missing': 'ID ɗin tabbatarwa ba ta nan. Da fatan za a nemi sabon lambar.',
      'verification_failed': 'An kasa tabbatarwa. Da fatan za a sake gwadawa.',
      'unexpected_error': 'An sami kuskure marar tsammani. Da fatan za a sake gwadawa daga baya.',
      'user_data_not_found': 'Bayanan mai amfani ba a samu ba a rikodin rajista.',
      'error_prefix': 'Kuskure',
      'payment_failed': 'Biya ya gaza',
      'new_password': 'Sabuwar Kalmar Sirri',
      'confirm_new_password': 'Tabbatar da Sabuwar Kalmar Sirri',
      'retype_password': 'Sake shigar da kalmar sirri',
      'passwords_do_not_match': 'Kalmar sirri ba su dace ba.',
      'location_name_hint': 'misali, Babban Wuri, Shagon A',
      'enter_name': 'Shigar da suna',
      'address_hint': 'Sunan titi, Gunduma, Birni',
      'enter_address': 'Shigar da adireshi',
      'enter_otp_prefix': 'Shigar da lambar sirri da aka aika zuwa ',
      'enter_otp_suffix': '. Wannan yana taimakawa tsaro.',
      'resend_available': 'Za a iya sake aikawa bayan',
      'resend_code': 'SAKE AIKA LAMBAR',
      'verify_continue': 'Tabbatar kuma ci gaba',
      'welcome': 'Barka da zuwa OptiFlow!',
      'select_role': 'Zaɓi matsayin ku.',
      'continue': 'Ci gaba',
      'business_setup': 'Saita Kasuwancin ku',
      'business_name': 'Sunan Kasuwanci',
      'business_type': 'Nau\'in Kasuwanci',
      'country_ops': 'Ƙasar Gudanarwa',
      'currency': 'Kuɗi',
      'primary_city': 'Babban Birni',
      'complete_setup': 'Kammala Saita',
      'phone_error': 'Shigar da lambar waya daidai',
      'otp_error': 'Shigar da lambar guda 6',
      'secure_sync': 'TSARO SYNC',
      'instant_sms': 'SMS NA TAKE',
      'step': 'Mataki',
      'business_setup_subtitle': 'Faɗa mana game da kasuwancin ku.',
      'manufacturing': 'Masana\'antu',
      'distribution': 'Rarrabawa',
      'business_owner': 'Mai Kasuwanci',
      'manager': 'Manaja',
      'driver': 'Direba',
      'admin': 'Admin',
      'role_owner_desc': 'Gudanar da kadarori da dabarun kasuwanci.',
      'role_manager_desc': 'Inganta samarwa ko rarraba kaya.',
      'role_driver_desc': 'Gudanar da hanyoyi da isar da sako.',
      'role_admin_desc': 'Gudanar da dukan manhajar baki daya.',
      'full_name': 'Cikakken Suna',
      'email_address': 'Adreshin E-mail',

      // Home
      'home_title': 'OptiFlow',
      'welcome_user_prefix': 'Sannu',
      'dashboard_subtitle': 'Shirye kake don inganta aikin ka?',
      'total_products': 'DUKAN\nKAYAYYAKI',
      'active_locations': 'WURAREN\nAIKI',
      'savings_mtd': 'AJIYA\n(MTD)',
      'ops_optimization': 'Inganta Ayyuka',
      'recent_results': 'Sakamakon Karshe',
      'home_tab': 'Gida',
      'view_all': 'Duba Duka',
      'last_optimization': 'INGANTAWA TA KARSHE',
      'network_strength': 'KARFIN SADARWA',
      'operational_resilience': 'Juriya ta Aiki',
      'saved_results': 'Sakamakon Da Aka Ajiye',
      'search_scenarios': 'Nemo...',
      'all': 'Duka',
      'product_mix': 'Mix na Samfura',
      'transport': 'Sufuri',
      'routes': 'Hanyoyi',
      'budget': 'Kasafi',
      'efficiency_gain': 'Karin Inganci',
      'savings_identified': 'Ajiya Da Aka Samu',
      'profile': 'Bayanai',
      'activity_stats': 'Kididdigar Aiki',
      'contact_info': 'Bayanin Tuntuɓa',
      'phone_number': 'LAMBAR WAYA',
      'location': 'WURI',
      'business_details': 'Bayanin Kasuwanci',
      'sign_out': 'Fita',

      // Product Mix
      'optimization': 'Ingantawa',
      'products': 'Kayayyaki',
      'resources': 'Albarkatu',
      'search_products': 'Nemo kayayyaki...',
      'add_product': 'Ƙara Samfuri',
      'add_new_product': 'Sabuwar Samfuri',
      'unit_type': 'Nau\'in Raka\'a',
      'unit_financials': 'Kudade',
      'selling_price': 'FARASHIN SIYARWA',
      'production_cost': 'KUDIN SAMARWA',
      'save_product': 'Ajiye Samfuri',
      'resource_constraints': 'Iyakokin Albarkatu',
      'save_resources': 'Ajiye Albarkatu',
      'allocation': 'Rarraba',
      'optimal_plan': 'Tsarin Karshe',
      'total_profit': 'RIBA DUKA',
      'production_breakdown': 'Rarraba Samfura',
      'export_pdf': 'Fitar da PDF',
      'share_whatsapp': 'Aika zuwa WhatsApp',

      // Transport
      'transport_cost_input': 'Kudin Sufuri',
      'history': 'Tarihi',
      'border_crossing': 'KETARE IYAKA',
      'supply_points': 'Wuraren Kaya',
      'factories': 'MASANA\'ANTU',
      'available_supply': 'KAYAN DA AKE DASHI',
      'add_supply_point': 'Ƙara Wurin Kaya',
      'demand_points': 'Wuraren Bukata',
      'retailers': 'YAN KOLI',
      'run_transport_opt': 'Inganta Sufuri',
      'add_location': 'Ƙara Wuri',
      'save_location': 'Ajiye Wuri',
      'opt_complete': 'AN KAMMALA INGANTAWA',
      'total_distance': 'NISAN TAFIYA',
      'fuel_required': 'MAN FETUR',
      'plan_routes': 'Tsara Hanyoyi',

      // Route
      'route_planner': 'Mai Tsara Hanya',
      'est_time': 'LOKACI',
      'optimize_route': 'Inganta Hanya',
      'start_navigation': 'Fara Tafiya',
      'save_route': 'Ajiye Hanya',
      'confirm_delivery': 'Tabbatar da Isarwa',
      'digital_signature': 'Sa Hannu',
      'submit_proof': 'Aika Tabbatarwa',
      'arrived': 'Na Isa',

      // Budget
      'budget_constraints_title': 'Iyakokin Kasafi',
      'run_budget_opt': 'Inganta Kasafi',
      'apply_budget': 'Aiwatar da Kasafi',
      'expected_roi': 'RIBAR DA AKE TSAMMANI',

      // Driver
      'good_morning': 'Ina kwana,',
      'ready_today_routes': 'Shirye don tafiya?',
      'syncing_offline': 'Sync bayanan offline...',
      'today_summary': 'Tarihin yau',
      'deliveries': 'Isar da kaya',
      'drive_time': 'Lokacin tuki',
      'distance': 'Nisan tafiya',
      'stops_left': 'SAURAN TSAYAWA',
      'pending_routes': 'Hanyoyin da suka rage',
      'completed': 'An gama',
      'start_delivery': 'Fara Isarwa',
      'today_routes': 'Hanyoyin Yau',
      'assigned_logistics': 'Logistics din da aka ba',
      'priority_route': 'HANYAR FIFIKO',
      'rural_route': 'HANYAR KAUYE',
      'offline_maps_avail': 'TASWIRAR OFFLINE TANA AKWAI',
      'view_details': 'Duba cikakken bayani',
      'refresh_routes': 'Sake duba hanyoyi',
      'join_fleet': 'Shiga rukunin motoci',
      'enter_code': 'Shigar da lambar kamfani',
      'fleet_id_hint': 'misali: OPT-ABC-123',
      'join': 'Shiga',
      'invalid_code': 'Lamba bata da kyau',

      // Settings
      'settings': 'Saituna',
      'language': 'Harshe',
      'notifications': 'Sanarwa',
      'offline_maps': 'Taswirar Offline',
      'clear_cache': 'GOGE CACHE',
      'save_changes': 'Ajiye Saituna',
      'contact_support': 'Tuntuɓi Tallafi',
      'report_issue': 'Kai Kara',
      'rate_app': 'Ba da Tauraro',

      // Admin
      'admin_dashboard': 'Bayanin Shugaba',
      'total_users': 'Dukan Masu Amfani',
      'active_businesses': 'Kasuwanci Masu Aiki',
      'user_mgmt': 'Gudanar da Masu Amfani',
      'sys_settings': 'Saitunan Tsarin',
      'broadcast': 'Aika Sanarwa Duka',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'fr', 'ha'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

// Custom Material Localizations for Hausa (Fallback to English if needed)
class _HausaMaterialLocalizationsDelegate extends LocalizationsDelegate<MaterialLocalizations> {
  const _HausaMaterialLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => locale.languageCode == 'ha';

  @override
  Future<MaterialLocalizations> load(Locale locale) async => GlobalMaterialLocalizations.delegate.load(const Locale('en'));

  @override
  bool shouldReload(covariant LocalizationsDelegate<MaterialLocalizations> old) => false;
}

// Custom Cupertino Localizations for Hausa (Fallback to English if needed)
class _HausaCupertinoLocalizationsDelegate extends LocalizationsDelegate<CupertinoLocalizations> {
  const _HausaCupertinoLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => locale.languageCode == 'ha';

  @override
  Future<CupertinoLocalizations> load(Locale locale) async => GlobalCupertinoLocalizations.delegate.load(const Locale('en'));

  @override
  bool shouldReload(covariant LocalizationsDelegate<CupertinoLocalizations> old) => false;
}

// Custom Widgets Localizations for Hausa (Fallback to English if needed)
class _HausaWidgetsLocalizationsDelegate extends LocalizationsDelegate<WidgetsLocalizations> {
  const _HausaWidgetsLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => locale.languageCode == 'ha';

  @override
  Future<WidgetsLocalizations> load(Locale locale) async => GlobalWidgetsLocalizations.delegate.load(const Locale('en'));

  @override
  bool shouldReload(covariant LocalizationsDelegate<WidgetsLocalizations> old) => false;
}

// Export specific Hausa delegates
const HausaMaterialLocalizationsDelegate = _HausaMaterialLocalizationsDelegate();
const HausaCupertinoLocalizationsDelegate = _HausaCupertinoLocalizationsDelegate();
const HausaWidgetsLocalizationsDelegate = _HausaWidgetsLocalizationsDelegate();
